// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	Name string `json:"name"`
}

type Query struct {
}

type User struct {
	Email string `json:"email"`
}
