package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/ballinwza/be-pradit-dnd-2025/internal/graph/model"
)

// AbilityDetailByShort is the resolver for the abilityDetailByShort field.
func (r *queryResolver) AbilityDetailByShort(ctx context.Context, short model.AbilityShortType) (*model.AbilityDetail, error) {
	return r.AbilityDetailService.GetAbilityDetailByShort(ctx, short)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
