package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"net/http"

	"github.com/ballinwza/be-pradit-dnd-2025/internal/error_handler"
	"github.com/ballinwza/be-pradit-dnd-2025/internal/graph/model"
)

// SaveCharacter is the resolver for the saveCharacter field.
func (r *mutationResolver) SaveCharacter(ctx context.Context, data model.SaveCharacterReq) (bool, error) {
	result, err := r.CharacterService.SaveCharacter(ctx, &data)
	if err != nil {
		return false, error_handler.NewValidationError("Failed to SaveCharacter", err, http.StatusInternalServerError).GqlError(ctx)
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
