package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"net/http"

	"github.com/ballinwza/be-pradit-dnd-2025/internal/error_handler"
	"github.com/ballinwza/be-pradit-dnd-2025/internal/graph/model"
)

// LevelList is the resolver for the levelList field.
func (r *queryResolver) LevelList(ctx context.Context) ([]*model.Level, error) {
	levelListModel, err := r.LevelService.GetLevelList(ctx)
	if err != nil {
		return nil, error_handler.NewValidationError("Failed to get LevelList", err, http.StatusInternalServerError).GqlError(ctx)
	}

	return levelListModel, nil
}
